sample_configurables = {
'SMS-T2bW' : {
  'legend' : 'SMS-T2bW',
  'color'  : 4,
  'style'  : 1,
  'width'  : 3,
  'fill'  : None,
  'fill_style'  : None,
             },
'TTJets'   : {
  'legend' : 't#bar{t}+jets',
  'color'  : 26,
  'style'  : 1001,
  'width'  : 3,
  'fill'   : 26,
  'fill_style'   : 26,
             },
}

######   configuration template   ######
"""
'Null'    : {
  'xlabel'  : None,
  'ylabel'  : None,
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
"""
######  end template  ######
plot_configurables = {
'PT_jet'    : {
  'xlabel'  : 'jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'loose_PT_jet'    : {
  'xlabel'  : 'loose b-jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'medium_PT_jet'    : {
  'xlabel'  : 'medium b-jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'tight_PT_jet'    : {
  'xlabel'  : 'tight b-jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'PT_S_jet'    : {
  'xlabel'  : 'S jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'loose_PT_S_jet'    : {
  'xlabel'  : 'loose S b-jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'medium_PT_S_jet'    : {
  'xlabel'  : 'medium S b-jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'tight_PT_S_jet'    : {
  'xlabel'  : 'tight S b-jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'PT_ISR_jet'    : {
  'xlabel'  : 'ISR jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'loose_PT_ISR_jet'    : {
  'xlabel'  : 'loose ISR b-jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'medium_PT_ISR_jet'    : {
  'xlabel'  : 'medium ISR b-jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'tight_PT_ISR_jet'    : {
  'xlabel'  : 'tight ISR b-jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'N_S_jet'    : {
  'xlabel'  : 'N S jets',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'N_loose_S_jet'    : {
  'xlabel'  : 'N loose S b-jets',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'N_medium_S_jet'    : {
  'xlabel'  : 'N medium S b-jets',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'N_tight_S_jet'    : {
  'xlabel'  : 'N tight S b-jet',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'N_ISR_jet'    : {
  'xlabel'  : 'N ISR jets',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'N_loose_ISR_jet'    : {
  'xlabel'  : 'N loose ISR b-jets',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'N_medium_ISR_jet'    : {
  'xlabel'  : 'N medium ISR b-jets',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'N_tight_ISR_jet'    : {
  'xlabel'  : 'N tight ISR b-jets',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'weight'    : {
  'xlabel'  : 'event weights',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : -1.,
  'xmax'    : 1.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
            },
'RISR'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 1.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'RISR_PTISR'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'p_{T}^{ISR} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'RISR_PTCM'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'p_{T}^{CM} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'PTISR_PTCM'    : {
  'xlabel'  : 'p_{T}^{ISR}',
  'ylabel'  : 'p_{T}^{CM} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'dphi_PTCM'    : {
  'xlabel'  : '#Delta #phi',
  'ylabel'  : 'p_{T}^{CM} [GeV]',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : np.pi,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'dphi_PTCM_div_PTISR'    : {
  'xlabel'  : '#Delta #phi',
  'ylabel'  : 'p_{T}^{CM} / p_{T}^{ISR}',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : np.pi,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
}
plot_configurables_old = {
'PT_jet'    : {
  'xlabel'  : 'jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'loose_PT_jet'    : {
  'xlabel'  : 'loose b-jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'medium_PT_jet'    : {
  'xlabel'  : 'medium b-jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'tight_PT_jet'    : {
  'xlabel'  : 'tight b-jet p_{T} [GeV]',
  'ylabel'  : 'jets',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'weight'    : {
  'xlabel'  : 'event weights',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : -1.,
  'xmax'    : 1.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
            },
'RISR'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 1.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'loose_RISR'    : {
  'xlabel'  : 'R_{ISR} w/ #geq1 loose b-jets',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 1.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'medium_RISR'    : {
  'xlabel'  : 'R_{ISR} w/ #geq1 medium b-jets',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 1.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'tight_RISR'    : {
  'xlabel'  : 'R_{ISR} w/ #geq1 tight b-jets',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 1.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'PTCM'    : {
  'xlabel'  : 'p_{T} CM [GeV]',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'loose_PTCM'    : {
  'xlabel'  : 'p_{T} CM w/ #geq1 loose b-jets [GeV]',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'medium_PTCM'    : {
  'xlabel'  : 'p_{T} CM w/ #geq1 medium b-jets [GeV]',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'tight_PTCM'    : {
  'xlabel'  : 'p_{T} CM w/ #geq1 tight b-jets [GeV]',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'PTISR'    : {
  'xlabel'  : 'p_{T} ISR [GeV]',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'loose_PTISR'    : {
  'xlabel'  : 'p_{T} ISR w/ #geq1 loose b-jets [GeV]',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'medium_PTISR'    : {
  'xlabel'  : 'p_{T} ISR w/ #geq1 medium b-jets [GeV]',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'tight_PTISR'    : {
  'xlabel'  : 'p_{T} ISR w/ #geq1 tight b-jets [GeV]',
  'ylabel'  : 'events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'RISR_jetpt'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'jet p_{T} [GeV]',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 1.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'loose_RISR_jetpt'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'loose b-jet p_{T} [GeV]',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 1.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'medium_RISR_jetpt'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'medium b-jet p_{T} [GeV]',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 1.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'tight_RISR_jetpt'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'tight b-jet p_{T} [GeV]',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 1.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'PTCM_jetpt'    : {
  'xlabel'  : 'p_{T} CM [GeV]',
  'ylabel'  : 'jet p_{T} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'loose_PTCM_jetpt'    : {
  'xlabel'  : 'p_{T} CM [GeV]',
  'ylabel'  : 'loose b-jet p_{T} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'medium_PTCM_jetpt'    : {
  'xlabel'  : 'p_{T} CM [GeV]',
  'ylabel'  : 'medium b-jet p_{T} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'tight_PTCM_jetpt'    : {
  'xlabel'  : 'p_{T} CM [GeV]',
  'ylabel'  : 'tight b-jet p_{T} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'PTISR_jetpt'    : {
  'xlabel'  : 'p_{T} ISR [GeV]',
  'ylabel'  : 'jet p_{T} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'loose_PTISR_jetpt'    : {
  'xlabel'  : 'p_{T} ISR [GeV]',
  'ylabel'  : 'loose b-jet p_{T} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'medium_PTISR_jetpt'    : {
  'xlabel'  : 'p_{T} ISR [GeV]',
  'ylabel'  : 'medium b-jet p_{T} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
'tight_PTISR_jetpt'    : {
  'xlabel'  : 'p_{T} ISR [GeV]',
  'ylabel'  : 'tight b-jet p_{T} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
}
